# Generated by Django 3.1.4 on 2020-12-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20201205_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='favourite',
            new_name='favorite',
        ),
    ]
